In [7]:
 #- Tạo ma trận:
import numpy as np
a = np.array(([(2,3,4), (4,6,8)],
              [(2,6,2), (3,6,2)],
              [(4,6,2), (4,7,0,)]), dtype = int)
print("Ma trận A= ",a)
  
  
  #- Tổng ,Hiệu 2 ma trận
import numpy as np
a = np.array(([(2,3,6), (2,8,4)]), dtype = int)
b = np.array(([(2,9,1), (7,5,8)]), dtype = int)
print("ma trận A+B= ", a+b)
print("ma trận A-B= ", a-b)


  #- tính tích 2 ma trận:
import numpy as np
C = "Tich 2 Ma Tran"
print(C)
a = np.array(([((1,2),(3,4)), ((5,3),(7,4))]), dtype = int)
b = np.array(([(5,7,7), (6,7,2)]), dtype = int)
print("ma trận C*D= ", a @ b)


   #- tính thương 2 ma trận:
import numpy as np
D = "Thuong 2 Ma Tran"
print(D)
a = np.array(([(5,10,6), (2,8,7)]), dtype = int)
b = np.array(([(2,6,1), (9,10,8)]), dtype = int)
print("ma trận A/B= ", a/b)


  


Ma trận A=  [[[2 3 4]
  [4 6 8]]

 [[2 6 2]
  [3 6 2]]

 [[4 6 2]
  [4 7 0]]]
ma trận A+B=  [[ 4 12  7]
 [ 9 13 12]]
ma trận A-B=  [[ 0 -6  5]
 [-5  3 -4]]
Tich 2 Ma Tran
ma trận C*D=  [[[17 21 11]
  [39 49 29]]

 [[43 56 41]
  [59 77 57]]]
Thuong 2 Ma Tran
ma trận A/B=  [[2.5        1.66666667 6.        ]
 [0.22222222 0.8        0.875     ]]
